# Generated by Django 4.2.11 on 2024-05-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movie_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img_path',
            field=models.ImageField(upload_to=''),
        ),
    ]
