# Generated by Django 4.2.11 on 2024-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_genre_movie_mpaa_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
