# Generated by Django 4.2.11 on 2024-05-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mpaa_Rating',
            field=models.JSONField(),
        ),
    ]
